// Design tokens for ScrapSmart (kept here so all UI components share one source).
export const theme = {
  colors: {
    primary: "#1B5E3B",
    primaryLight: "#2E7D52",
    primaryPale: "#E8F5EE",
    accent: "#D4860A",
    accentLight: "#F5A623",
    accentPale: "#FEF3D7",
    danger: "#C0392B",
    dangerPale: "#FDECEA",
    surface: "#FAFAF7",
    card: "#FFFFFF",
    border: "#E0DDD5",
    text: "#1A1A1A",
    textMuted: "#6B7280",
    textLight: "#9CA3AF",
    success: "#15803D",
    successPale: "#DCFCE7",
    warning: "#B45309",
    warningPale: "#FEF3C7",
  },
};

export const T = {
  en: {
    appName: "ScrapSmart", tagline: "Your Smart Scrap Partner",
    schedule: "Schedule Pickup", prices: "Price List", myPickups: "My Pickups",
    dashboard: "Dashboard", collectors: "Collectors", settings: "Settings",
    pricePerKg: "per kg", requestPickup: "Request Pickup",
    selectMaterials: "Select Materials", enterAddress: "Enter Your Address",
    chooseTime: "Preferred Time",
    morning: "Morning (8–12)", afternoon: "Afternoon (12–4)", evening: "Evening (4–7)",
    confirm: "Confirm Pickup",
    statusRequested: "Requested", statusAccepted: "Accepted",
    statusCollected: "Collected", statusCompleted: "Completed",
    totalEarnings: "Total Earnings", totalCollected: "Total Collected (kg)",
    monthlyPickups: "Monthly Pickups", activeCollectors: "Active Collectors",
    nearestCollector: "Nearest Collector",
    rating: "Rating", pickups: "Pickups",
    verified: "Verified", topRated: "Top Rated",
    selectLang: "Language", weight: "Weight (kg)", amount: "Amount (₹)",
    paymentMode: "Payment", cash: "Cash", upi: "UPI",
    adminPanel: "Admin Panel", updatePrices: "Update Prices",
    save: "Save", raiseDispute: "Raise Dispute",
    disputeDesc: "Describe your issue", submit: "Submit", cancel: "Cancel",
    priceHistory: "Price History", materialBreakdown: "Material Breakdown",
    collectorPerformance: "Collector Performance",
    offlineMode: "Offline Mode", syncData: "Sync Data",
    estimatedAmount: "Estimated Amount", viewReceipt: "View Receipt",
    notifications: "Notifications", hello: "Hello",
    householdUser: "Household User", scrapCollector: "Scrap Collector",
    shopAdmin: "Shop Admin",
  },
  ta: {
    appName: "ScrapSmart", tagline: "உங்கள் புத்திசாலி குப்பை கூட்டாளி",
    schedule: "பிக்கப் திட்டமிடு", prices: "விலை பட்டியல்", myPickups: "என் பிக்கப்கள்",
    dashboard: "டாஷ்போர்டு", collectors: "சேகரிப்பாளர்கள்", settings: "அமைப்புகள்",
    pricePerKg: "கிலோவுக்கு", requestPickup: "பிக்கப் கோரு",
    selectMaterials: "பொருட்களை தேர்ந்தெடு", enterAddress: "உங்கள் முகவரி",
    chooseTime: "விருப்பமான நேரம்",
    morning: "காலை (8–12)", afternoon: "மதியம் (12–4)", evening: "மாலை (4–7)",
    confirm: "பிக்கப் உறுதிப்படுத்து",
    statusRequested: "கோரப்பட்டது", statusAccepted: "ஏற்கப்பட்டது",
    statusCollected: "சேகரிக்கப்பட்டது", statusCompleted: "முடிந்தது",
    totalEarnings: "மொத்த வருமானம்", totalCollected: "மொத்தம் சேகரித்தது (கிலோ)",
    monthlyPickups: "மாதாந்திர பிக்கப்கள்", activeCollectors: "செயலில் சேகரிப்பாளர்கள்",
    nearestCollector: "அருகிலுள்ள சேகரிப்பாளர்",
    rating: "மதிப்பீடு", pickups: "பிக்கப்கள்",
    verified: "சரிபார்க்கப்பட்டது", topRated: "சிறந்த மதிப்பீடு",
    selectLang: "மொழி", weight: "எடை (கிலோ)", amount: "தொகை (₹)",
    paymentMode: "கட்டணம்", cash: "பணம்", upi: "UPI",
    adminPanel: "நிர்வாக குழு", updatePrices: "விலைகளை புதுப்பிக்கவும்",
    save: "சேமி", raiseDispute: "புகாரளி",
    disputeDesc: "உங்கள் பிரச்சனையை விவரி", submit: "சமர்ப்பி", cancel: "ரத்துசெய்",
    priceHistory: "விலை வரலாறு", materialBreakdown: "பொருள் விவரம்",
    collectorPerformance: "சேகரிப்பாளர் செயல்திறன்",
    offlineMode: "ஆஃப்லைன் முறை", syncData: "தரவை ஒத்திசை",
    estimatedAmount: "மதிப்பிடப்பட்ட தொகை", viewReceipt: "ரசீதை பார்க்கவும்",
    notifications: "அறிவிப்புகள்", hello: "வணக்கம்",
    householdUser: "குடும்ப பயனர்", scrapCollector: "குப்பை சேகரிப்பாளர்",
    shopAdmin: "கடை நிர்வாகி",
  },
};

export const getStatusColor = (s) => {
  if (s === "completed") return { bg: "#DCFCE7", text: "#15803D" };
  if (s === "accepted") return { bg: "#FEF3C7", text: "#B45309" };
  if (s === "requested") return { bg: "#DBEAFE", text: "#1D4ED8" };
  return { bg: "#F3F4F6", text: "#6B7280" };
};
